Senparc.Weixin/Senparc.Weixin/Helpers/SerializerHelper.cs
Senparc.Weixin/Senparc.Weixin/Senparc.Weixin.csproj
Senparc.Weixin/Senparc.Weixin/packages.config

Reverts JeffreySu/WeiXinMPSDK#122

Revert "JavaScriptSerializer不能正确解析ExpandoObject对象，修改为是用json.net"

---

Senparc.Weixin.QY/Senparc.Weixin.QY/AdvancedAPIs/LoginAuth/LoginAuthApi.cs
Senparc.Weixin.QY/Senparc.Weixin.QY/AdvancedAPIs/MailList/MailListApi.cs
Senparc.Weixin.QY/Senparc.Weixin.QY/Enums.cs
Senparc.Weixin/Senparc.Weixin/Config.cs
Senparc.Weixin/Senparc.Weixin/Helpers/SerializerHelper.cs
Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/Get.cs

更新登陆 授权接口方法
企业号通讯录扩容后，存在Json长度不够的情况，添加参数以解决此问题

更新登陆 授权接口方法

---

RunPack.ps1
Senparc.Weixin.sln
src/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension/project.json
src/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension/project.lock.json
src/Senparc.Weixin.MP/Senparc.Weixin.MP/project.json
src/Senparc.Weixin.MP/Senparc.Weixin.MP/project.lock.json
src/Senparc.Weixin.QY/Senparc.Weixin.QY/project.json
src/Senparc.Weixin.QY/Senparc.Weixin.QY/project.lock.json
src/Senparc.Weixin/Senparc.Weixin/Context/MessageQueue.cs
src/Senparc.Weixin/Senparc.Weixin/project.json

一些微小的调整，还是同步一下吧，免得差距太大

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/Senparc.Weixin.MP.csproj
src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/RequestHandler.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/ResponseHandler.cs

漏push了两个文件

---

src/Senparc.Weixin.Open/Senparc.Weixin.Open/Senparc.Weixin.Open.csproj
src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Tester/TesterApi.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Tester/TesterJson/TesterResultJson.cs

开放平台-小程序-成员管理

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Scan/ScanApi.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Scan/ScanJson/ProductGetQrCodeJsonResult.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Senparc.Weixin.MP.csproj

官方文档 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1455872062

增加获取商品二维码支持

---

src/Senparc.Weixin/Senparc.Weixin/Entities/Request/Extensions/RequestMessageTextExtension.cs

不匹配，才调用默认方法。

---

src/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Senparc.Weixin.MP.CoreSample.csproj
src/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Views/OAuth2/Index.cshtml
src/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Views/OpenOAuth/Index.cshtml
src/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Views/TenPayV3/JsApi.cshtml
src/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Views/TenPayV3/ProductItem.cshtml
src/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Views/TenPayV3/ProductList.cshtml
src/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Views/WeixinJSSDK/Index.cshtml

1. set App_Data\Document\Config.xml always copy to output directory.
2. use <script> instead of Render method in view. The old method is not supported any more in core version.
3. Change Senparc.Weixin.MP.Sample.Models to Senparc.Weixin.MP.CoreSample.Models in some views.
4. In core version, Request is different from the framework verison. Fixed some problem of Request usage.

Fix some problems for net core version

---

src/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/wwwroot/Scripts/senparc.menu.js
src/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Scripts/senparc.menu.js

fix自定义菜单设置

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/CommonAPIs/CommonApi.Menu.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/JsonResult/GetMenuResultFull.cs

Fix #969，修正GetMenu()方法返回菜单内容为始终为NULL的问题

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/TenPayV3/TenPayV3ReverseRequestData.cs

TenPayV3ReverseRequestData 未初始化 PackageRequestHandler 对象，调用时报错

TenPayV3ReverseRequestData 未初始化 PackageRequestHandler 对象，调用时报错

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/Entities/JsonResult/WeixinUserInfoResult.cs

MP v14.10.4 WeixinUserInfoResult添加tagid_list属性（用户被打上的标签ID列表） 感谢@zhouxin93

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/CommonAPIs/Menu/CommonApi.Menu.Common.cs

自定义菜单使用JSON数据更新引发空引用异常

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work.Test/AdvancedAPIs/Chat/ChatTest.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work.net45.sln
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/Chat/ChatApi.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/Chat/ChatJson/SendChatMessageData.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Enums.cs

https://work.weixin.qq.com/api/doc#13308
企业微信支持企业自建应用通过接口创建群聊并发送消息到群，让重要的消息可更及时推送给群成员，方便协同处理。应用消息仅限于发送到通过接口创建的内部群聊，不支持添加企业外部联系人进群。此接口暂时仅支持企业内接入使用。
https://github.com/JeffreySu/WeiXinMPSDK/commit/f6db7df34045afe57b098bf017c1b521b4f3088a82
https://github.com/JeffreySu/WeiXinMPSDK/compare/master...pekrr1e:master#diff-a51d3eb7879aa0cfe371137281c2ac0e
https://github.com/JeffreySu/WeiXinMPSDK/compare/master...pekrr1e:master#diff-d5864d6ce8410310bcc7c52f775bebe
https://github.com/JeffreySu/WeiXinMPSDK/compare/master...pekrr1e:master#diff-2dbcd5549afaabd19520e12fd738ead
https://github.com/JeffreySu/WeiXinMPSDK/compare/master...pekrr1e:master#diff-ee10ef1c3d5aba196c58d541ed5a989ee

新增企业微信群聊会话功能支持：https://work.weixin.qq.com/api/doc#13308

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Card/CardAPI.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Custom/CustomApi.cs
src/Senparc.Weixin/Senparc.Weixin/Helpers/Conventers/WeixinJsonConventer.cs
src/Senparc.Weixin/Senparc.Weixin/Helpers/SerializerHelper.cs

在.NET4.5下测试以下几个接口均可正常处理
创建会员卡，设置开卡字段，获取开卡组件链接，激活微信会员卡
有.NET3.5适配，但是没有合适的环境测试

使用Newtonsoft.Json改写json序列化

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/Chat/ChatApi.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/Chat/ChatJson/ChatResult.cs

创建会话返回结果 #1227 

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/Helpers/EntityHelper.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/RequestMessageFactory.cs
src/Senparc.Weixin/Senparc.Weixin/Utilities/EntityUtility/EntityUtility.cs

通讯录变更事件,解决变更后不能走CommonService中的逻辑

通讯录变更事件,解决变更后不能走CommonService中的逻辑

---

src/Senparc.Weixin.Open/Senparc.Weixin.Open/ComponentAPIs/ComponentApi.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/ComponentAPIs/ComponentJson/QueryAuthResult.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Enums.cs

Fixes #1158 
Docs https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN

增加第三方平台授权接口的授权类型字段

---

Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/TenPayV3Controller.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/TenPayV3Info.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/TenPayV3InfoCollection.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.cs

“只是修改了V3支付部分信息

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/AdvancedAPIs/Media/MediaTest.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/CommonAPIs/CommonApiTest.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/Utilities/Senparc.Weixin.Utilities.HttpUtility/GetTests.cs
src/Senparc.Weixin.MP/Senparc.WeixinTests/BaseTest.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work.Test/CommonApis/CommonApiTest.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen.Tests/AdvancedAPIs/WxApp/WxAppApiTests.cs

在测试代码中 增加缺少的 NETSTANDARD2_0 编译条件

在测试代码中 增加缺少的 NETSTANDARD2_0 编译条件

---

src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSetting.cs
src/Senparc.Weixin/Senparc.Weixin/RegisterServices/SenparcWeixinRegisterServiceExtension.cs
src/Senparc.Weixin/Senparc.Weixin/WeixinRegister.cs

有三处地方缺少 用到 NETCOREAPP2_0 和 NETCOREAPP2_1 的地方缺少 NETSTANDARD2_0 编译条件。

增加缺少的 NETSTANDARD2_0 的编译条件

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/AdvancedAPIs/Card/CardAPITest.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Card/Common/Card_BaseInfo/Card_BaseInfoBase.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Senparc.Weixin.MP.vs2017.csproj

Developer #1556

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Card/CardCreate/CardCreateData.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Card/CardManage/BaseCardUpdateInfo.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Card/CardManage/CardUpdateData.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Card/Common/Card_BaseInfo/Card_BaseInfoBase.cs

添加会员卡数据和卡券基本数据里的跳转小程序参数字段
微信文档url https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025283

添加卡券跳转小程序参数

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/Senparc.Weixin.MP.csproj

.net4.5 包含SendMenuContent.cs文件

.net4.5 包含SendMenuContent.cs文件

---

Samples/Senparc.Weixin.MP.Sample.Consoles/Senparc.Weixin.MP.Sample.Consoles/Program.cs
Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Startup.cs
src/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension.vs2017.csproj
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Comment/CommentApi.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/AccessTokenContainer.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/JsApiTicketContainer.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/OAuthAccessTokenContainer.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/WxCardApiTicketContainer.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Senparc.Weixin.MP.vs2017.csproj
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Containers/AuthorizerContainer.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Containers/ComponentContainer.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Register.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Senparc.Weixin.Open.vs2017.csproj
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay.vs2017.csproj
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Containers/AccessTokenContainer.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Containers/JsApiTicketContainer.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Containers/ProviderTokenContainer.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Senparc.Weixin.Work.vs2017.csproj
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Containers/SessionContainer.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen.vs2017.csproj
src/Senparc.Weixin/Senparc.Weixin/Containers/BaseContainer.cs
src/Senparc.Weixin/Senparc.Weixin/Senparc.Weixin.vs2017.csproj

Developer async container

---

src/Senparc.Weixin.Open/Senparc.Weixin.Open/Senparc.Weixin.Open.csproj
src/Senparc.Weixin/Senparc.Weixin/WeixinRegister.cs

Reverts JeffreySu/WeiXinMPSDK#1747

Revert " 解决Sample解决方案调试错误"

---

Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Controllers/AnalysisController.cs
Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Senparc.Weixin.MP.CoreSample.csproj
Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample.CommonService/Senparc.Weixin.MP.CoreSample.CommonService.csproj
src/Senparc.Weixin.Cache/Senparc.Weixin.Cache.Memcached/Senparc.Weixin.Cache.Memcached.vs2017.csproj
src/Senparc.Weixin.Cache/Senparc.Weixin.Cache.Redis/Senparc.Weixin.Cache.Redis.vs2017.csproj
src/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension.vs2017.csproj
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Senparc.Weixin.MP.vs2017.csproj
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Senparc.Weixin.Open.vs2017.csproj
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/TenPayV3InfoCollection.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Senparc.Weixin.Work.vs2017.csproj
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen.vs2017.csproj
src/Senparc.Weixin/Senparc.Weixin/Senparc.Weixin.vs2017.csproj

https://github.com/JeffreySu/WeiXinMPSDK/issues/1762

发布新版本，支持.NET动态多证书加载

---

appveyor.yml
src/Directory.Build.props

https://github.com/JeffreySu/WeiXinMPSDK/issues/1772
https://ci.appveyor.com/project/hanabi1224/weixinmpsdk/builds/24733228/artifacts

Generate .snupkg on build

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/User/UserJson/UserInfoJson.cs

临时二维码场景值经过测试其实是usigned int，不然传递超过int32的值会报异常！

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/User/UserJson/UserInfoJson.cs

Reverts JeffreySu/WeiXinMPSDK#1793

Revert "临时二维码场景值经过测试其实是usigned int，不然传递超过int32的值会报异常！"

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/OAuthAccessTokenContainer.cs

Reverts JeffreySu/WeiXinMPSDK#1858

Revert "Issue1857"

---

Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample.CommonService/Senparc.Weixin.MP.Sample.CommonService.csproj
Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample.CommonService/packages.config
Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample.Tests/Senparc.Weixin.MP.Sample.Tests.csproj
Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample.Tests/packages.config
Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample.csproj
Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/packages.config
src/Senparc.WebSocket/src/Senparc.WebSocket/Senparc.WebSocket/Senparc.WebSocket.csproj
src/Senparc.Weixin.Cache/Senparc.Weixin.Cache.Memcached/Senparc.Weixin.Cache.Memcached.csproj
src/Senparc.Weixin.Cache/Senparc.Weixin.Cache.Redis/Senparc.Weixin.Cache.Redis.csproj
src/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension.csproj
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Senparc.Weixin.MP.csproj
src/Senparc.Weixin.MP/Senparc.WeixinTests/BaseTest.cs
src/Senparc.Weixin.MP/Senparc.WeixinTests/Senparc.WeixinTests.csproj
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Senparc.Weixin.Open.csproj
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay.csproj
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Senparc.Weixin.Work.csproj
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen.csproj
src/Senparc.Weixin/Senparc.Weixin/Senparc.Weixin.csproj

更新 .net 4.5 Sample 的 nuget 引用

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/Entities/Result/MiniAppRedPackResult.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/RedPackApi/RedPackApi.cs

MiniApp RedPack API

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/Enums.cs

自动回复规则缺少卡券枚举

---

.gitignore
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/Event/RequestMessageEvent_ExternalContact.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Enums.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageContext/DefaultWorkMessageContext.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageHandlers/WorkMessageHandler.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Senparc.Weixin.Work.csproj

添加企业微信外部联系人事件

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/ExternalApi.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/GroupChatGetResult.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/GroupChatListParam.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/GroupChatListResult.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/MailList/Member/MemberResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Tcb/TcbApi.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Tcb/TcbJson/CreateIndex.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Tcb/TcbJson/WxDatabaseJsonResult.cs

新增小程序和企业微信的API，并Fix #2060

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/Entities/Request/TenpayV3ProfitShareingRequestData.cs

接口版本号 version 是 String(32) 1.0 新增字段，接口版本号，区分原接口，默认填写1.0。入参新增version后，则支付通知接口也将返回单品优惠信息字段promotion_detail，请确保支付通知的签名验证能通过。

接口版本号 version 是 String(32) 1.0 新增字段

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/Event/RequestMessageEvent_ExternalContact.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageContext/DefaultWorkMessageContext.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageHandlers/WorkMessageHandler.cs

添加企业内部开发外部联系人 编辑企业客户事件 回调事件

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/Entities/Request/TenPayV3UnifiedorderRequestData.cs

PackageRequestHandler.SetParameter("version", Register.TenpayV3ProtfitRequestDataVersion);   订单优惠时区分优惠商品时必需，

订单优惠时区分优惠商品时必需

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay.netcore3.csproj
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/Entities/Request/TenpayV3ProfitShareingRequestData.cs

v1.5.502.3 fix bug:必须指定待分账的接收方列表 判断有误 #2184 感谢 @houta-higuchi  @fanheshe

---

src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Code/CodeApi.cs

https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/code/undocodeaudit.html

代小程序开发 添加撤回审核接口

---

src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Helpers/EncryptHelper.cs

修改文件：Senparc.Weixin.WxOpen.Helpers.EncryptHelper类
新增方法：DecryptPhoneNumberBySessionKey
解密手机号(根据sessionKey解密)，并转换为DecodedPhoneNumber实体。

新增-解密手机号(根据sessionKey解密)

---

.gitignore
Samples/net45-mvc/Senparc.Weixin.MP.Sample.CommonService/Senparc.Weixin.NetCore3Sample.CommonService.csproj
src/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension.netcore3.csproj
src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/Helpers/EntityHelperTest.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Entities/Request/Event/RequestMessageEvent_MassSendJobFinish.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Senparc.Weixin.MP.netcore3.csproj
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Senparc.Weixin.Open.netcore3.csproj
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Senparc.Weixin.Work.netcore3.csproj
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen.netcore3.csproj
src/Senparc.Weixin/Senparc.Weixin/Senparc.Weixin.netcore3.csproj

MASSSENDJOBFINISH事件增加 ArticleUrlResult 节点

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work.Test/EntityHelperTest.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/GetExternalContactResult.cs

https://work.weixin.qq.com/api/doc/90000/90135/92114
#2337

补充企微获取客户详情接口返回值字段

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/ExternalApi.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/GetMomentListParam.cs

新增朋友圈api功能

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/ExternalApi.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/GroupWelcomeTemplateRequest.cs

添加企业微信入群欢迎语素材

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/Entities/Request/Event/RequestMessageEvent_Submit_Invoice_Title.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Enums.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/MessageHandlers/Async/MessageHandlerAsync.Event.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/MessageHandlers/MessageHandler.Event.cs

微信发票 /极速开发票 
5、接收用户提交的抬头
用户提交抬头后，商户会收到用户提交的事件。
文档地址：https://developers.weixin.qq.com/doc/offiaccount/WeChat_Invoice/Quick_issuing/Interface_Instructions.html

用户提交抬头后，商户会收到用户提交的事件。

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/BasePay/BasePayApis.cs

修复微信支付V3沙盒地址错误

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/Apis/Marketing/MarketingApisTests.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/NotifyJson/StockNotifyJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/CreateStockRequsetData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/SetNotifyUrlRequsetData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/ReturnJson/QueryCouponReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/ReturnJson/QueryCouponsReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.cs

完成营销工具中的优惠券接口
完成营销工具中的优惠券接口单元测试

完成营销工具中的优惠券接口

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Media/MediaApi.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/QrCode/QrCodeApi.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/CommonAPIs/CommonApi.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Code/CodeApi.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/Apis/BasePay/BasePayApisTests.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/CreateStockRequsetData.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/Media/MediaApi.cs

修复NcApiBind对Get方法的问题

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/OaDataOpen/OaDataOpenJson/GetCheckinDayDataJsonResult.cs

获取考勤日报数据接口返回结果

---

Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Controllers/HomeController.cs
Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Controllers/Weixin/TenPay/TenPayRealV3Controller.cs
Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Senparc.Weixin.Sample.Net6.csproj
Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Startup.cs
Samples/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayRealV3/JsApi.cshtml
readme.en.md
readme.md
src/Senparc.Weixin.Cache/Senparc.Weixin.Cache.CsRedis/Senparc.Weixin.Cache.CsRedis.net6.csproj
src/Senparc.Weixin.Cache/Senparc.Weixin.Cache.Redis/Senparc.Weixin.Cache.Redis.net6.csproj
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Media/MediaApi.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/QrCode/QrCodeApi.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/CommonAPIs/CommonApi.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Code/CodeApi.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Entities/NotifyReturnData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/CreateBusifavorStockRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/UseBusifavorCouponRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/ReturnJson/CreateBusifavorStockReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/ReturnJson/QueryBusifavorCouponReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/ReturnJson/QueryBusifavorCouponsReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/ReturnJson/QueryBusifavorStockReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/ReturnJson/UseBusifavorCouponReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Entities/JsApiUiPackage.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Helpers/TenPaySignHelper.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayNotifyHandler.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Senparc.Weixin.TenPayV3.net6.csproj
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/Media/MediaApi.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/OaDataOpen/OaDataOpenApi.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/OaDataOpen/OaDataOpenJson/GetCheckinDataJsonResult.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/OaDataOpen/OaDataOpenJson/GetCheckinDayDataJsonResult.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Senparc.Weixin.Work.net6.csproj

merge for JeffreySu/Developer
完成商家券部分实体类

完成商家券部分实体类 merge for JeffreySu/Developer

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/Apis/Marketing/MarketingApisTests.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/CreateBusifavorStockRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/ModifyBusifavorStockBudgetRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/ModifyBusifavorStockInformationRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/PayBusifavorReceiptsRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/ReturnBusifavorCouponRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/RequestData/UseBusifavorCouponRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/ReturnJson/ModifyBusifavorStockBudgetReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/Entities/ReturnJson/PayBusifavorReceiptsReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/UnfreezeProfitsharingRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/AddProfitsharingReceiverReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/CreateProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/DeleteProfitsharingReceiverReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/DownloadProfitsharingBillReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/QueryProfitsharingAmountsReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/QueryProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/QueryReturnProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/ReturnProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/ProfitsharingApis.cs

完成 商家券 模块单元测试

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/Apis/BusinessCircle/BusinessCircleApisTests.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/Apis/Complaint/ComplaintApisTests.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/Apis/Profitsharing/ProfitsharingApisTest.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/Apis/VehicleParking/VehicleParkingApisTest.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/BusinessCircle/BusinessCircleApis.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/BusinessCircle/Entities/RequestData/NotifyBusinessCirclePointsRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/PayScoreApis.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/VehicleParking/Entities/RequestData/CreateParkingRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/VehicleParking/Entities/RequestData/PayParkingRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/VehicleParking/VehicleParkingApis.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Entities/TenpayDateTime.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Helpers/TenPayDateTimeHelper.cs

完成微信支付V3微信支付分停车接口单元测试;
完成微信支付V3智慧商圈接口单元测试;
完成微信支付V3 消费者投诉2.0接口单元测试

完成TenpayV3接口单元测试

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Busifavor.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Card.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Favor.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Image.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Partnerships.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Paygift.cs

modified:   src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Busifavor.cs
modified:   src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Card.cs
modified:   src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Favor.cs
modified:   src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Image.cs
modified:   src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Partnerships.cs
modified:   src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Marketing/MarketingApis.Paygift.cs

添加TenPayV3.Apis.MarketingApis部分文件头注释

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayApiRequest.cs

不建议底层生产环境打印Console

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Draft/DraftApi.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Draft/DraftJson/AddDraftResultJson.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Draft/DraftJson/DraftModel.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Draft/DraftJson/GetDraftListResultJson.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Draft/DraftJson/GetDraftResultJson.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/FreePublish/FreePublishApi.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/FreePublish/FreePublishJson/FreePublishBatchGetResultJson.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/FreePublish/FreePublishJson/FreePublishGetArticleResultJson.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/FreePublish/FreePublishJson/GetFreePublishResultJson.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/FreePublish/FreePublishJson/SubmitFreePublishJson.cs
src/Senparc.Weixin.MP/Senparc.Weixin.MP/Senparc.Weixin.MP.netcore3.csproj

> 官方文档：https://developers.weixin.qq.com/doc/offiaccount/Draft_Box/Add_draft.html
> 官方文档：https://developers.weixin.qq.com/doc/offiaccount/Publish/Publish.html
#2499

微信接口 草稿箱和发布能力接口实现

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/Event/Approval/RequestMessageEvent_SysApprovalChange.cs

Senparc.NeuChar.Helpers.EntityHelper.FillEntityWithXml() failed at line 389 when the SpTime is not 0.

Change SpTime type from byte to uint

---

src/Senparc.Weixin.MP/Senparc.Weixin.MP.Test/OpenAPIs/OpenApiTests.cs
src/Senparc.Weixin/Senparc.Weixin/Helpers/JsonResultHelper.cs
src/Senparc.Weixin/Senparc.Weixin/Senparc.Weixin.net6.csproj

1、更新 TryCommonApiBase 异常抛出逻辑
2、添加 JsonResultHelper
3、更新 ReturnCode 枚举，OpenApi 中的错误代码

Senparc.Weixin v6.15.4

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/MailList/MailListApi.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/MailList/Member/GetMemberIdListResult.cs

获取企业成员的userid与对应的部门ID列表
官网文档地址 https://developer.work.weixin.qq.com/document/path/96067

增加企业微信获取成员ID列表的接口

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/Senparc.Weixin.Work.net7.csproj

1、添加应用“消息撤回”（PR #2793）
2、添加“上下游及互联企业”相关接口、“获取下级/下游企业小程序session”接口（PR #2794） 3、添加“审批”接口
4、添加“客户标签管理Api”接口，添加“任务卡片事件推送”事件（待完善）（PR #2414）

Work v3.15.16 （修改更新日志中的版本号）

---

src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen.Tests/AdvancedAPIs/Delivery/DeliveryApiTest.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryApi.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/AddOrderModel.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/BindAccountModel.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/CancelOrderModel.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/GetOrderModel.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/GetPathModel.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/GetQuotaModel.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/AddOrderJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/BatchGetOrderJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/BindAccountJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/CancelOrderJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/GetAllAccountJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/GetAllDeliveryJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/GetOrderJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/GetPathJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/GetPrinterJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/GetQuotaJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/TestUpdateOrderJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/JsonResult/UpdatePrinterJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/TestUpdateOrderModel.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Delivery/DeliveryJson/UpdatePrinterModel.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Entities/Request/Event/RequestMessageEvent_AddExpressPath.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Enums.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/MessageHandlers/WxOpenMessageHandler.Event.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen.net6.sln

微信小程序物流服务相关接口和事件推送

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/RequestData/AssignGuideRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/RequestData/GoldplanChangeCustomPageStatusRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/RequestData/GoldplanChangeGoldplanStatusRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/RequestData/GoldplanCloseAdvertisingShowRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/RequestData/GoldplanOpenAdvertisingShowRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/RequestData/GoldplanSetAdvertisingIndustryFilterRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/RequestData/QueryGuideRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/RequestData/RegisterGuideRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/ReturnJson/GoldplanChangeCustomPageStatusReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/ReturnJson/GoldplanChangeGoldplanStatusReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/ReturnJson/GoldplanCloseAdvertisingShowReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/ReturnJson/GoldplanOpenAdvertisingShowReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/Entities/ReturnJson/GoldplanSetAdvertisingIndustryFilterReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/PayScore/PayScoreApis.cs

文档：https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter8_5_5.shtml
功能：完善支付即服务、点金计划

微信支付v3 服务商 经营能力

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/AddProfitsharingReceiverRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/CreateProfitsharingRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/DeleteProfitsharingReceiverRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/FinishProfitsharingRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/QueryProfitsharingBillsRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/QueryProfitsharingConfigsRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/QueryProfitsharingRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/QueryReturnProfitsharingRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/ReturnProfitsharingRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/AddProfitsharingReceiverReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/CreateProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/DeleteProfitsharingReceiverReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/FinishProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/QueryProfitsharingBillsReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/QueryProfitsharingConfigsReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/QueryProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/QueryReturnProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/ReturnProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/ReturnJson/UnfreezeProfitsharingReturnJson.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/ProfitsharingApis.cs

文档：https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter8_1_1.shtml
功能：微信支付V3 服务商角色 资金应用 分账/品牌连锁分账

Feature/微信支付v3 服务商 资金应用

---

src/Senparc.Weixin.Open/Senparc.Weixin.Open/ComponentAPIs/ComponentApi.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Entities/Request/RequestMessageThirdFasteRegister.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/GetPrefetchDNSDomainData.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/SetPrefetchDNSDomainData.cs

解决几个Issues

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/BasePay/Entities/RequestData/TransactionsRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/BasePay/Entities/ReturnJson/OrderReturnJson.cs

1. 服务商模式下 payer的请求及返回参数增加
2. 基础支付请求增加support_fapiao

TenPayV3 基础支付参数缺失处理

---

Samples/TenPayV3/Senparc.Weixin.Sample.TenPayV3/Controllers/TenPayApiV3Controller.cs
Samples/TenPayV3/Senparc.Weixin.Sample.TenPayV3/Senparc.Weixin.Sample.TenPayV3.csproj
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/AddProfitsharingReceiverRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/Entities/RequestData/CreateProfitsharingRequestData.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/ProfitsharingApis.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Attributes/FieldEncryptAttribute.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Helpers/SecurityHelper.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayApiRequest.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Senparc.Weixin.TenPayV3.net6.csproj

TenPayV3 分账逻辑中，添加分账方以及进行分账的时候name需要加密处理，内部增加FieldEncryptAttribute，即自动加密处理

TenPayV3分账 字段内部加密

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/Event/RequestMessageEvent_ExternalContact.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/RequestMessageFactory.cs

文档地址：https://developer.work.weixin.qq.com/document/path/92277#%E6%B7%BB%E5%8A%A0%E4%BC%81%E4%B8%9A%E5%AE%A2%E6%88%B7%E4%BA%8B%E4%BB%B6

企业微信 成员对外联系 客户消息通知处理

---

src/Senparc.Weixin.Open/Senparc.Weixin.Open/Entities/Request/RequestMessageThirdFasteRegister.cs
src/Senparc.Weixin.Open/Senparc.Weixin.Open/Senparc.Weixin.Open.net6.csproj

Open三方推送消息枚举处理

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/BasePay/BasePayApis.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/BasePay/Entities/RequestData/RefundQueryRequestData.cs

服务商模式 V3退款订单查询 提示缺少sub_mchid #2954

---

src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayApi.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/CompleteComplaintRequestData.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/GetComplaintDetailJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/GetComplaintDetailRequestData.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/GetComplaintListJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/GetComplaintListRequestData.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/GetNegotiationHistoryJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/GetNegotiationHistoryRequestData.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/GetUploadFileSignJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/GetUploadFileSignRequestData.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/QueryAdverFundsJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/QueryFundsBillJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/QueryFundsBillRequestData.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/QueryRecoverBillJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/QueryRecoverBillRequestData.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/QueryUserBalanceJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/ResponseComplaintRequestData.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/UploadVpFileJsonResult.cs
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/XPay/XPayJson/UploadVpFileRequestData.cs

虚拟支付增加了接口从1.0.7~1.0.10，同步完善
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/industry/virtual-payment.html#_3-%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97

虚拟支付增加了接口从1.0.7~1.0.10，同步完善

---

src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/Event/RequestMessageEvent_TemplateCardClick.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/Enums.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageContext/DefaultWorkMessageContext.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageHandlers/Async/WorkMessageHandler.Async.cs
src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageHandlers/WorkMessageHandler.cs

Hi,@JeffreySu 
企业微信增加：模板卡片点击回调事件
有添加文件变更记录，帮忙看看是否可用

企业微信增加：模板卡片点击回调事件

---

Samples/TenPayV3/Senparc.Weixin.Sample.TenPayV3/Senparc.Weixin.Sample.TenPayV3.net8.csproj
Samples/TenPayV3/Senparc.Weixin.Sample.TenPayV3/appsettings.json
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Enums.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayHttpHandler.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Senparc.Weixin.TenPayV3.net8.csproj
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/TenPayHttpClient/Signer/SM3WithSM2Signer.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.Interfaces.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.cs

Sample.TenPayV3的appsetting中加入EncryptionType参数
Senparc.Weixin.TenpayV3的版本号1.3.1.1->1.3.1.2
SendAsync方法中增加appsetting中EncryptionType参数默认值的判断
ISenparcWeixinSettingForTenpayV3的EncryptionType参数的继承

Developer sm zmz 2024053102

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Enums.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayHttpHandler.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/TenPayHttpClient/Signer/SM3WithSM2Signer.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.Interfaces.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.cs

增加相关注释信息
增加TenPayV3Setting中的AuthrizationType属性

优化SM3WithSM2Sign方法

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Enums.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayHttpHandler.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/TenPayHttpClient/Signer/SM3WithSM2Signer.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.Interfaces.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.cs

Developer sm zmz 2024053001

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Enums.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayHttpHandler.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/TenPayHttpClient/Signer/SM3WithSM2Signer.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.Interfaces.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.cs

修改AuthrizationType为EncryptionType

Developer sm zmz 2024053101

---

src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Icp/IcpApi.cs

接口：https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/record/createIcpVerifyTask.html
无参数的情况下不能为null传递，设置为 new {}

icp verifytask dataformaterror

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/Apis/Profitsharing/ProfitsharingApisTest.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/Senparc.Weixin.TenPayV3.Test.net8.csproj
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3.Test/appsettings.json
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/BasePay/BasePayApis.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/Profitsharing/ProfitsharingApis.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Enums.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Helpers/SecurityHelper.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Helpers/TenPaySignHelper.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayApiRequest.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.Interfaces.cs
src/Senparc.Weixin/Senparc.Weixin/Entities/SenparcWeixinSettings/SenparcWeixinSettingItem.cs
src/Senparc.Weixin/Senparc.Weixin/Helpers/TenPay/TenPayHelper.cs

微信支付公钥替换文档：https://pay.weixin.qq.com/docs/merchant/products/update-pub-key/wxp-pub-key-guide.html
支持微信支付公钥以及平台证书

兼容微信支付公钥以及平台证书

---

readme.md
src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/WxApp/WxAppApi.cs

https://developers.weixin.qq.com/minigame/dev/api-backend/open-api/qr-code/wxacode.getUnlimited.html
page参数实际不对，应该是path

Feature/wxacode unlimit参数修改

---

src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Apis/BasePay/BasePayApis.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Entities/JsApiUiPackage.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/Helpers/TenPaySignHelper.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayApiRequest.cs
src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPayV3/HttpHandlers/TenPayNotifyHandler.cs

兼容微信平台证书和微信支付公钥 
优化 在切换时间段的时候，兼容两种

tenpayv3 兼容微信平台证书和微信支付公钥
