- Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/User/UserAPI.cs
添加用户备注信息更新接口。
开发者可以通过该接口对指定用户设置备注名，该接口暂时开放给微信认证的服务号
> 更新UserAPI.cs

- Senparc.Weixin/Senparc.Weixin/Helpers/SerializerHelper.cs
- Senparc.Weixin/Senparc.Weixin/Senparc.Weixin.csproj
- Senparc.Weixin/Senparc.Weixin/packages.config
JavaScriptSerializer不能正确解析ExpandoObject对象，修改为是用json.net。  
json.net也一样是开源的，类库来自NuGet
> JavaScriptSerializer不能正确解析ExpandoObject对象，修改为是用json.net

- Senparc.Weixin.Open/Senparc.Weixin.Open/CommonAPIs/CommonApi.cs
- Senparc.Weixin.Open/Senparc.Weixin.Open/CommonAPIs/JsApiTicketContainer.cs
- Senparc.Weixin.Open/Senparc.Weixin.Open/Entities/JsonResult/JsApiTicketResult.cs
第三方平台开发者代替公众号使用JS
SDK，3、通过config接口注入权限验证配置，但在获取jsapi_ticket时，不通过公众号的access_token来获取，而是通过第三方平台的授权公众号token（公众号授权给第三方平台后，第三方平台通过“接口说明”中的api_authorizer_token接口得到的token），来获取获取jsapi_ticket，然后使用这个jsapi_ticket来得到signature，进行JS
SDK的配置和开发。注意JS SDK的其他配置中，其他信息均为正常的公众号的资料（而非第三方平台的）。
> 第三方平台使用JS-SDK获取jsapi_ticket

- src/Senparc.Weixin/Senparc.Weixin/Utilities/EntityUtility/EntityUtility.cs
修正 `EntityUtility.ConvertTo<T>()` 扩展方法非 `NET45` 时逻辑判断错误，此错误会导致 `NETCore` 下运行时 new 任何 `MessageHandler` 子类时会报错 `This operation is only valid on generic types`.
> 修正 NETCore 下 MessageHandler 失效问题

- .github/ISSUE_TEMPLATE.md
- readme.md
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/QrCode/QrCodeApi.cs
问题现象：
当使用QRCode_ActionName.QR_STR_SCENE生成临时二维码，创建成功的二维码的有效时间永远是60秒。
问题原因：
QrCodeApi忘记了在QR_STR_SCENE下设置有效时间。
> 解决了QrCode_ActionName.QR_STR_SCENE下临时二维码有效时间expire_seconds不生效的Bug.

- src/Senparc.Weixin.Work/Senparc.Weixin.Work.sln
- src/Senparc.Weixin/Senparc.Weixin/Utilities/WeixinUtility/ApiUtility.cs
第一次使用贡献代码，不大会用，嘻嘻。
言归正转，经测试企业微信AccessToken的长度已增加到300，原ApiUtility.IsAppId方法存在错误
> 修复企业微信AccessToken长度加长导致的BUG

- src/Senparc.Weixin/Senparc.Weixin/Trace/WeixinTrace.cs
> 多次 LogBegin 会导致 缩进 对不齐。

- src/Senparc.Weixin.Work/Senparc.Weixin.Work/CommonAPIs/CommonApi.cs
- src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/RequestUtility.Get.cs
- src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/RequestUtility.Post.cs
1. In core version. Although **_webproxy** is defined, it's not used.
So, **RequestUtility.SetHttpProxy** will never do it's work correctly.
2. Replace **CommonJsonSend.Send** with  **Senparc.Weixin.CommonAPIs.CommonJsonSend.Send** in **CommonApi.cs**.
Because **CommonJsonSend.Send** is clearly defined as an obsolete function.
**_This pull request fixed the above problems._**
> Enable WebProxy in core version

- Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Startup.cs
- src/Senparc.Weixin.MP.MvcExtension/Senparc.Weixin.MP.MvcExtension/Utilities/HttpUtility/EnableRequestRewind.cs
- src/Senparc.Weixin/Senparc.Weixin/Utilities/HttpUtility/RequestUtility.Post.cs
在Senparc.Weixin.MP.MvcExtension中提供EnableRequestRewind中间件，开启netcore2的RequestRewind模式令Request.Body可以二次读取，以解决某些特殊情况下netcore默认机制导致的Request.Body为空而引发的WeixinSDK错误的问题。#1090
> 在Senparc.Weixin.MP.MvcExtension中提供EnableRequestRewind中间件

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/ResponseHandler.cs
在.NetCore环境下，ResponseHandler方法中，不能用new DefaultHttpContext()代替客户端请求时创建的HttpContext；
这个接口调试特别困难，千万别出错！
> 修复.NetCore环境下的一个BUG

- Samples/Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/TenPayV3Controller.cs
trade_type=NATIVE时，OpenId应该为null，
示例代码中错误的把productId当作OpenId传进去了
> 示例代码参数传输错误

- Samples/Senparc.Weixin.MP.Sample.vs2017/Senparc.Weixin.MP.CoreSample/Controllers/TenPayV3Controller.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/ResponseHandler.cs
解决.NetCore环境微信支付回调时ResponseHandler传入HttpContext实例后解析xml提示找不到根节点的错误.
> 解决.NetCore环境微信支付回调时ResponseHandler传入HttpContext实例后解析xml提示找不到根节点的错误.

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLib/ClientResponseHandler.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLib/ResponseHandler.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/ResponseHandler.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/TenPayV3Api/RedPackApi/RedPackApi.Via.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/TenPayV3Api/RedPackApi/RedPackApi.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/Tencent/Sample.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/Tencent/WXBizMsgCrypt.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/Tencent/Sample.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/Tencent/WXBizMsgCrypt.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/TenPayLib/ResponseHandler.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/Tencent/Sample.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/Tencent/WXBizMsgCrypt.cs
- src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/Tencent/WXBizMsgCrypt.cs
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5
根据说明,将所有XmlDocument的地方
var xmlDoc = new XmlDocument();
xmlDoc.XmlResolver = null; // 添加这一行代码
> 国外爆出的XXE安全漏洞，以及 微信支付团队的说明如下：

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/Entities/Request/TenPayV3RefundQueryRequestData.cs
在微信退款的API请求实体中，对subMchId错误的初始化，导致微信返回错误：**sub_mch_id参数长度有误**
未发布新版本的nuget之前的修复方式为：
```
var request = new TenPayV3RefundQueryRequestData(***params***);
request.SubMchId =***your sub mch id***;//该步骤是可省略的，可直接将下面一行代码的requestSubMchId 替换为你的submchid
request.PackageRequestHandler.SetParameter("sub_mch_id", request.SubMchId);
request.PackageRequestHandler.SetParameter("sign", request.PackageRequestHandler.CreateMd5Sign("key", request.Key));
```
> Wrong constructor initialization of refund query request

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/Entities/Request/TenPayV3MicroPayRequestData.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/TenPayLibV3/RequestHandler.cs
微信支付现支持HMAC-SHA256签名方式（EncryptHelper.GetHmacSha256方法留待实现）
https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=4_3
**添加 Senparc.Weixin.MP.TenPayLibV3.RequestHandler.CreateSha256Sign(string key, string value) 方法**
**修改 Senparc.Weixin.MP.TenPayLibV3.TenPayV3MicroPayRequestData 构造函数中 Sign签名方式，添加Sha256**
其余支付实体对象同理修改
Signed-off-by: 554393109 <554393109@qq.com>
> 微信支付现已支持HMAC-SHA256签名方式

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Invoice/InvoiceApi.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Invoice/InvoiceJson/InvoicePlatformData.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Invoice/InvoiceJson/InvoicePlatformResultJson.cs
报销方发票代码都检查过了，就报销方实体定义误用了开票平台实体
> 修正发票信息实体，区分开票平台提交的发票信息实体与报销方获取的发票信息实体

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Analysis/AnalysisResultJson/ArticleAnalysisItemJson.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Comment/CommentApi.cs
1.  添加回复时content内容未传给微信
2. 删除回复时不需要传输content参数
```
{
"ref_date": "2019-07-03",
"msgid": "2650799822_1",
"title": " 你会怎么安排孩子的假期？",
"user_source": 0,
"details": [
...
],
"url": "https:\/\/mp.weixin.qq.com\/s?__biz=MjM5OTI2MjA2MQ==&mid=2650799822&idx=1&sn=633ddcf0b0b8a4af2b151fbd17e0cfe3#rd"
},
```
> 回复评论的参数bug，图文群发总数据的新字段添加

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Custom/CustomApi.cs
1.  【异步方法】客服输入状态的参数bug
2. 调整客服输入状态的参数名称
> 微信文档地址：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140547
> fix【异步方法】客服输入状态的参数bug，调整客服输入状态的参数名称

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/WxCardApiTicketContainer.cs
GetWxCardApiTicketAsync方法中ticket过期，重新获取时type值错误。默认为“jsapi”，卡券使用wx_card
> 卡券WxCardApiTicketContainer【异步方法】获取可用Ticket,type传值的问题

- src/Senparc.Weixin.TenPay/Senparc.Weixin.TenPay/V3/Universal/Entities/Result/TenPayV3Results.cs
相关 Issue #1902 
新增的payment_time字段没有被赋值，使用payment_time的时候是Null
>  商户的企业付款查询结果实体（GetTransferInfoResult）payment_time字段空值修复

- src/Senparc.Weixin/Senparc.Weixin/Enums.cs
添加40164的错误编码
调用接口的IP地址不在白名单中，请在接口IP白名单中进行设置。（小程序及小游戏调用不要求IP地址在白名单内。）
https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Get_access_token.html
> 添加40164的错误编码

- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/NewTmpl/NewTmplApi.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/NewTmpl/NewTmplJson/AddTemplateJsonResult.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/NewTmpl/NewTmplJson/GetPubTemplateKeyWordsByIdJsonResult.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/NewTmpl/NewTmplJson/GetPubTemplateTitlesJsonResult.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/NewTmpl/NewTmplJson/GetTemplateListJsonResult.cs
- src/Senparc.Weixin/Senparc.Weixin/CommonAPIs/CommonJsonSend.cs
1. 小程序实现订阅消息管理
接口文档：https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.addTemplate.html
2. 小程序订阅消息接口几个POST请求的接口不支持Stream流传递，特使用Dictionary<string, string>
该方式只是基于当前的框架实现，建议底层POST请求开放Content-Type出来，以及支持HttpContent的传递，这样让使用者更加的灵活
> 小程序实现订阅消息的管理

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/Invoice/InvoiceJson/InvoiceData.cs
```
{
"s_pappid": "appid",
"order_id": "1234",
"money": 11,
"timestamp": 1474875876,
"source": "web",
"redirect_url": "https://mp.weixin.qq.com",
"type": 1,
"ticket": "ticket"
}
```
当source设置为枚举时，提交到微信接口的source值变成了数字，导致接口报错。
> 获取授权页链接数据开票来源改为string，枚举在提交数据的时候会变成数字，导致接口调用失败

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/TemplateMessage/TemplateApi.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/TemplateMessage/TemplateMessageJson/TempleteModel/SubscribeMsgTempleteModel.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/AdvancedAPIs/TemplateMessage/TemplateMessageJson/TempleteModel/TempleteModel.cs
- src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Template/TemplateApi.cs
- src/Senparc.Weixin.WxOpen/src/Senparc.Weixin.WxOpen/Senparc.Weixin.WxOpen/AdvancedAPIs/Template/TemplateJson/TempleteModel.cs
修正模板消息的相关代码命名错误，应为”Templ**a**te“ ，而不是"Templ**e**te"
> Fix "templete“ to ”template“

- src/Senparc.Weixin.Work/Senparc.Weixin.Work.Test/EntityHelperTest.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/GroupChatGetResult.cs
[获取客户群详情](https://work.weixin.qq.com/api/doc/90000/90135/92122)  接口返回值有变化。
其中外部联系人在微信开放平台的唯一身份标识（微信unionid）这个字段很重要。 
@JeffreySu  是否可以优先发布下
> 补充获取客户群详情结果字段

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/Entities/Request/Event/RequestMessageEvent_MassSendJobFinish.cs
- src/Senparc.Weixin.MP/Senparc.Weixin.MP/Entities/Request/Event/RequestMessageEvent_TemplateSendJobFinish.cs
因消息排重时使用接口IRequestMessageEventBase定义的MsgId进行排重键判定，当不指定具体实现类时MsgId值则为零，若使用通讯的PostModel签名作为排重依据，则在已处理的消息链表中表现较为混乱
> RequestMessageEventBase子类请求对象MsgID字段赋值时，同时赋值父类MsgId

- .gitignore
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/AdvancedAPIs/External/ExternalJson/GetExternalContactInfoBatchResult.cs
[https://developer.work.weixin.qq.com/document/path/92994](url)
> 调整批量获取客户详情返回值

- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainApi.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/GetEffectiveDomainResultJson.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/GetEffectiveWebViewDomainResultJson.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/GetPrefetchDNSDomainResultJson.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/GetWebViewDomainConfirmFileResultJson.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/ModifyDomainDirectlyResultJson.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/ModifyDomainResultJson.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/SetPrefetchDNSDomainData.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/SetPrefetchDNSDomainResultJson.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/SetWebViewDomainDirectlyResultJson.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/Domain/DomainJson/SetWebViewDomainResultJson.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/ModifyDomain/ModifyDomainApi.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/SetWebViewDomain/SetWebViewDomainApi.cs
完善第三方平台API-待商家管理小程序-小程序域名管理所有接口
https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/domain-management/modifyServerDomain.html
1. 增加
快速配置小程序服务器域名
获取业务域名校验文件
快速配置小程序业务域名
获取发布后生效服务器域名列表
获取发布后生效业务域名列表
获取DNS预解析域名
设置DNS预解析域名
2. 修改
设置其他的两个API为Obsolete
> 完善第三方平台API-待商家管理小程序-小程序域名管理所有接口

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/Containers/AccessTokenContainer.cs
all other RegisterAsync has .ConfigureAwait(false), except AccessTokenContainer, cause when run in winform mode, it cause ui dead lock for 10 seconds.
> avoid ui dead lock

- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/SecurityJson/ApplySetOrderPathInfo.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/SecurityJson/ApplySetOrderPathInfoJsonResult.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/SecurityJson/GetOrderPathInfoJsonResult.cs
- src/Senparc.Weixin.Open/Senparc.Weixin.Open/WxaAPIs/WxaApi.cs
订单页 path 信息 获取与设置
获取：
[获取](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/basic-info-management/getOrderPathInfo.html)
[设置](https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/basic-info-management/applySetOrderPathInfo.html)
> 订单页path信息 单独设置

- src/Senparc.Weixin.MP/Senparc.Weixin.MP/CommonAPIs/CommonApi.cs
> https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/getStableAccessToken.html
POST https://api.weixin.qq.com/cgi-bin/stable_token
请求示例1（不传递force_refresh，默认值为false）:
```
{
"grant_type": "client_credential",
"appid": "APPID",
"secret": "APPSECRET"
}
```
请求示例2（设置force_refresh为false）:
```
{
"grant_type": "client_credential",
"appid": "APPID",
"secret": "APPSECRET",
"force_refresh": false
} 
```
> 添加获取稳定版接口调用凭据GetStableAccessToken

- src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/ThirdPartyInfo/RequestMessageInfo_Reset_Permanent_Code.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/ThirdPartyInfo/RequestMessager_Register_Corp.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/Enums.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageHandlers/Async/WorkMessageHandler.Async.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageHandlers/WorkMessageHandler.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/RequestMessageFactory.cs
1. 修复Async方法循环调用的Bug
2. 增加三方操作: RESET_PERMANENT_CODE
3. REGISTER_CORP处理事件明明问题修复(破坏性变更， 已做提示，再更新编译时报错，提示需要修复)
> 企业微信三方代开发处理事件: 修复Async方法循环调用的Bug

- src/Senparc.Weixin.Work/Senparc.Weixin.Work/Entities/Request/Event/RequestMessageEvent_MsgAuditNotify.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/Enums.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageContext/DefaultWorkMessageContext.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageHandlers/Async/WorkMessageHandler.Async.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/MessageHandlers/WorkMessageHandler.cs
- src/Senparc.Weixin.Work/Senparc.Weixin.Work/RequestMessageFactory.cs
MessageHandler中间件增加事件 会话存档-产生会话回调事件(MSGAUDIT_NOTIFY)类型回调
模块：Work 企业微信
事件类型: MSGAUDIT_NOTIFY 会话存档-产生会话回调事件
文档地址：https://developer.work.weixin.qq.com/document/path/95039
> 企业微信中间件增加:会话存档-产生会话回调事件回调

- src/Senparc.Weixin.Open/Senparc.Weixin.Open/OAuthAPIs/OAuthJson/OAuthAccessTokenResult.cs
第三方平台网页授权返回值也增加了  is_snapshotuser 和  unionid参数
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html
`{
"access_token":"86_8ltlLHY7eIXre1qb8XAL3MyiiVIqCPAOM4t6A077MzI-Q",
"expires_in":7200,
"refresh_token":"86_4_m8T_72NxQwfROhxC0FjA-9ChOyTblGB69pQ",
"openid":"oUSqc6cEcBI2fiO76sZDVgSVN0rY",
"scope":"snsapi_userinfo",
"unionid":"oeA830tP2C2EzJPoSBQBdCNg8Iw0",
"is_snapshotuser":1
}
`
> Senparc.Weixin.Open.OAuthAPIs 返回值添加参数 is_snapshotuser 和 unionid
